language: node_js

node_js:
  - "10.7.0"
  - "node"
install:
  - npm i
  
service:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE free-mentors;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD '0703625710';" -U postgres

cache:
  directories:
  - node_modules
script:
  - npm run test
after_success:
  -npm run coverage